# mkdocs.yml
site_name: Docker Scout CLI Documentation
site_url: https://narutosi77.github.io/scout-cli/
repo_url: https://github.com/narutosi77/scout-cli
repo_name: narutosi77/scout-cli
edit_uri: blob/main/docs/ # Este apunta a la carpeta donde est치n tus .md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: es
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

nav:
  - Home: index.md
  - Comandos:
    - Escanear Vulnerabilidades: comandos/scout_cves.md
    - Comparar Im치genes: comandos/scout_compare.md
    - An치lisis R치pido: comandos/scout_quickview.md

plugins:
  - search