# .github/workflows/generate_docs.yaml
name: Build and Deploy Docs

on:
  push:
    branches:
      - main # Desplegar cuando se haga push a la rama principal
    paths: # Solo ejecutar si cambian archivos relevantes a la documentación
      - 'docs/**'
      - 'mkdocs.yml'
      - 'Dockerfile.docs'
      - 'generate_docs.py'
      - 'requirements.txt' # Asegúrate de tener este archivo con las dependencias
      - '.github/workflows/generate_docs.yaml'
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde la UI de GitHub

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necesario para actions/checkout y para actions/upload-pages-artifact
      pages: write # Permiso necesario para desplegar en GitHub Pages
      id-token: write # Permiso para autenticación OIDC, requerido por actions/deploy-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image for Docs Generator
        # Corregido para usar Dockerfile.docs
        run: docker build -t scout-docs-generator -f Dockerfile.docs .

      - name: Create temporary container and copy generated docs
        run: |
          CONTAINER_ID=$(docker create scout-docs-generator)
          docker cp $CONTAINER_ID:/app/site/. ./site_output # MkDocs genera en 'site' por defecto
          docker rm $CONTAINER_ID

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages # Este nombre es requerido por actions/deploy-pages
          path: './site_output'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4