name: Create Release and Build Binaries

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to release (e.g., v1.0.0)"
        required: true
        type: string

jobs:
  call-build-binaries:
    # Llamada al workflow reutilizable ubicado en el mismo repositorio
    uses: ./.github/workflows/release_cli_binaries.yaml
    with:
      tag: ${{ github.ref_name || inputs.tag }}