# .github/workflows/trivy_security_scan.yaml
name: Trivy Security Scan (Public Image Test)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Necesario para subir resultados SARIF

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # OMITIMOS el paso de Log in to Docker Hub

      # OMITIMOS el paso de Build My CLI/Plugin Image for Scan
      # En su lugar, usaremos una imagen pública conocida

      - name: Run Trivy vulnerability scan on Public Image
        uses: aquasecurity/trivy-action@master
        with:
          # Escanea una imagen de Docker Hub pública (ej. nginx)
          image-ref: 'nginx:latest' # <--- CAMBIADO AQUÍ: Usamos una imagen pública
          format: 'sarif'
          output: 'trivy-report.sarif'
          exit-code: '1' # Falla si se encuentran vulnerabilidades CRITICAL/HIGH
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-report.sarif'

      - name: Upload Trivy report artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-security-report
          path: trivy-report.sarif